sudo: required

language: crystal

services:
  - docker

before_install:
  - docker build -t drujensen/chat-kemalyst .

script:
  - docker run drujensen/chat-kemalyst /bin/sh -c "cd /app/user; crystal spec"


